license="MIT"
modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/supermassimo/DynamicTreesPlus/issues"

[[mods]]
modId="dynamictreesplus"
version="${file.jarVersion}"
displayName="Dynamic Trees Plus"
updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/DynamicTreesPlus.json?raw=true"
displayURL="http://minecraft.curseforge.com/projects/dynamictreesplus"
logoFile="logo.png"
credits=""
authors="Ferreusveritas, Max Hyper/supermassimo, Harley O'Connor"
description='''
Vanilla addon for Dynamic Trees'''

[[dependencies.dynamictreesplus]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dynamictreesplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dynamictreesplus]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.20.1-1.3.0-BETA2,)"
    ordering="AFTER"
    side="BOTH"